### ISSUE TITLE
Keyboard cheatsheet says "Markdown Cheatsheet"

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/vala-tester#1]
Looks like a copy-paste issue from another app, maybe? It would probably be better to use Granite's markup accel tooltips for this: https://github.com/elementary/granite/blob/c6f47f11356c7241e31476336c9278b3c48d598a/lib/Widgets/Utils.vala#L158

Demo at https://github.com/elementary/granite/blob/c6f47f11356c7241e31476336c9278b3c48d598a/demo/Views/UtilsView.vala#L26

**Comment by unbelievableflavour** [comment]
I added that to the start button. But how do i do that for gtkmenuitems with labels?

**Comment by unbelievableflavour** [comment]
Nvm. This looks like what i want. https://developer.gnome.org/gtk3/stable/GtkAccelLabel.html

**Comment by unbelievableflavour** [comment]
Fixed it.
