### ISSUE TITLE
Change requested for AppCenter: Vala logo icon

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/vala-tester#2]
Hey @bartzaalberg, thanks for submitting your app to AppCenter! However, after a review, we decided to ask for a change before the app is released to users: your app's icon appears to be the Vala logo, which may imply an official endorsement or official status of your app. We'd like to request that you modify your app icon, i.e. with a badge or alternate emblem, so that it does not look as close to the official Vala logo.

**Comment by unbelievableflavour** [comment]
Whoops, my bad. Apparently i didn't push the new logo. I will check it when i get home.

**Comment by unbelievableflavour** [comment]
I added the logo, can you check if its fine?

**Comment by unbelievableflavour** [comment]
I'm just gonna push the release and see :)
