### ISSUE TITLE
Forgotten "Vala" in logo?

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/vala-tester#3]
I noticed the AppCenter shows this weird part right of your logo:
![screenshot from 2019-03-04 12-26-32 2x](https://user-images.githubusercontent.com/523210/53730645-d611d000-3e78-11e9-860b-22bd679fa71b.png)

Opening your logo file and adding a green rectangle behind it becomes clear it contains an extra "Vala" text:
![screenshot from 2019-03-04 12-25-37 2x](https://user-images.githubusercontent.com/523210/53730671-eb86fa00-3e78-11e9-9f61-6985926b6804.png)

**Comment by unbelievableflavour** [comment]
Fixed this. Has been released and checked. Closing this.
