### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by btd1337** [bartzaalberg/vala-tester#4]
I will support your application in Arch Linux. Please, consider to use 2 branchs: master (stable code), develop (development code).

Please add a section containing the following instruction:

## Arch Linux
Arch Linux users can find `Vala Tester` under the name [vala-tester-git](https://aur.archlinux.org/packages/vala-tester-git/) in the **AUR**:

`$ aurman -S vala-tester-git`

**Comment by unbelievableflavour** [comment]
You created the fix yourself. So i guess this ticket can be closed.
