### ISSUE TITLE
The Hello World Example does not work due to the absence of compiler's parameters

### ISSUE THREAD

**Issue by saidbakr** [bartzaalberg/vala-tester#7]
This example should works:
```
public class MyApp : Gtk.Application{

    public MyApp () {
        Object (
            application_id: "com.github.saidbakr.gtk-hello",
            flags: ApplicationFlags.FLAGS_NONE
        );
    }
    
    protected override void activate () {
        var button_hello = new Gtk.Button.with_label ("Click Me...");
        button_hello.margin = 12;        
        button_hello.clicked.connect (() => {
            button_hello.label = "Hello World!";
            button_hello.sensitive = false;
        });
        var main_window = new Gtk.ApplicationWindow(this);
        main_window.default_height = 300;
        main_window.default_width = 300;
        main_window.title = "Hello World!";
        main_window.add(button_hello);
        main_window.show_all();
    }
    
    public static int main (string[] args){
        var app = new MyApp ();
        return app.run(args);
    }

}
```
But it returns **`valatest.vala:1.22-1.24: error: The symbol Gtk' could not be found`**. The Language, I think, select menu should be supplied with another menu or text field to supply parameters to the compiler `valac` to do something like: `valac --pkg gtk+-3.0 ...`

**Comment by marbetschar** [comment]
Just ran into the same issue - would be awesome to add this possibility. Maybe just start with a hardcoded `--pkg gtk+-3.0` as a quick fix?

I guess - especially at the beginning - it would be nice to have the ability to tinker with Gtk.

**Comment by unbelievableflavour** [comment]
I'm sorry I don't run Elementary OS anymore. But if you guys could offer an MR and test it I would be happy to merge and create a release for you!

**Comment by unbelievableflavour** [comment]
Oh, just see you offered an MR! Nice!
